- name: Initiate Development Pipeline
  hosts: sejam_server
  gather_facts: False

  vars_prompt:
      - name: "githubuser"
        prompt: "Enter your github username"
        private: no
      - name: "githubpassword"
        prompt: "Enter your github password"
        private: yes


  #sudo: True
  tasks:
     - name: remove existing src directory
       become: True
       file:
         state: absent
         path: /home/ubuntu/se_jam

     - name: check out github repo
       git: repo=https://{{ githubuser }}:{{ githubpassword }}@github.com/jeffthorne/se_jam.git dest=/home/ubuntu/se_jam


     - name: Change into src dir
       command: chdir=/home/ubuntu/se_jam/docker-flask-app ls

     - name: Shutting down containers
       become: True
       service:
         name: docker
         state: stopped

     - name: Initializing Docker Engine
       become: True
       service:
         name: docker
         state: started

     - name: Build container
       become: True
       command: chdir=/home/ubuntu/se_jam/docker-flask-app docker build -t web-app-one:latest .

     - name: Run container
       become: True
       command: chdir=/home/ubuntu/se_jam/docker-flask-app docker run --dns=8.8.8.8 -d -p 8080:5001 web-app-one
