- name: Initiate Development Pipeline
  hosts: sejam_server

#  vars_prompt:
#    - name: "githubuser"
#      prompt: "Enter your github username"
#      private: no
#    - name: "githubpassword"
#      prompt: "Enter your github password"
#      private: yes


  #sudo: True
  tasks:
     - name: copy test file
       become: true
       copy: src=test.txt dest=/home/ubuntu/test.txt
